export const goals = [
  {
    _id: "goal_1",
    title: "Goal 1",
    description: "A sample Goal",
    createdAt: "",
    updatedAt: "",
    checkpoints: [
      {
        _id: "checkpoint_1",
        title: "Checkpoint 1",
        description: "A goal to achieve",
        createdAt: "",
        updatedAt: "",
        tasks: [
          {
            _id: "task_1",
            title: "Task 1",
            completed: true,
            description: "A sample task",
            createdAt: "",
            updatedAt: "",
          },
          {
            _id: "task_2",
            title: "Task 2",
            completed: false,
            description: "A sample task",
            createdAt: "",
            updatedAt: "",
          },
          {
            _id: "task_3",
            title: "Task 3",
            completed: false,
            description: "A sample task",
            createdAt: "",
            updatedAt: "",
          },
          {
            _id: "task_4",
            title: "Task 4",
            completed: false,
            description: "A sample task",
            createdAt: "",
            updatedAt: "",
          },
        ],
      },
      {
        _id: "checkpoint_2",
        title: "Checkpoint 2",
        description: "A goal to achieve",
        createdAt: "",
        updatedAt: "",
        tasks: [
          {
            _id: "task_1",
            title: "Task 1",
            description: "A sample task",
            completed: false,
            createdAt: "",
            updatedAt: "",
          },
          {
            _id: "task_2",
            title: "Task 2",
            description: "A sample task",
            completed: false,
            createdAt: "",
            updatedAt: "",
          },
          {
            _id: "task_3",
            title: "Task 3",
            description: "A sample task",
            completed: false,
            createdAt: "",
            updatedAt: "",
          },
          {
            _id: "task_4",
            title: "Task 4",
            description: "A sample task",
            completed: false,
            createdAt: "",
            updatedAt: "",
          },
        ],
      },
    ],
  },
  {
    _id: "goal_2",
    title: "Goal 2",
    description: "Another Goal to achieve",
    createdAt: "",
    updatedAt: "",
    checkpoints: [
      {
        _id: "checkpoint_1",
        title: "Checkpoint 1",
        description: "A sample checkpoint",
        createdAt: "",
        updatedAt: "",
        tasks: [
          {
            _id: "task_1",
            title: "Task 1",
            description: "A sample task",
            completed: false,
            createdAt: "",
            updatedAt: "",
          },
          {
            _id: "task_2",
            title: "Task 2",
            description: "A sample task",
            completed: false,
            createdAt: "",
            updatedAt: "",
          },
          {
            _id: "task_3",
            title: "Task 3",
            description: "A sample task",
            completed: false,
            createdAt: "",
            updatedAt: "",
          },
          {
            _id: "task_4",
            title: "Task 4",
            description: "A sample task",
            completed: false,
            createdAt: "",
            updatedAt: "",
          },
        ],
      },
    ],
  },
];
